flysystem:
    storages:
        default:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/local'
        products:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/local/products'
        test:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/temp/'